### ISSUE TITLE
Some Typos

### ISSUE THREAD

**Issue by peterchang0414** [boazbk/crypto#10]
- Page 18: third-to-last line: "... perfectly secure regardless **of** the attacker's computational resources.
- Page 26: sixth-to-last line: "More precisely, this means that for every natural number _k_, there are  (not ->) **more** than _k_ primes.
- Page 27: second paragraph, second-to-last line: "... to be a number that is (divisable ->) **divisible** neither **by** p,q, nor r, and more generally ... is not (divisable ->) **divisible** by..."

**Comment by boazbk** [comment]
Thanks so much William!
