### ISSUE TITLE
Length of ciphertext: o vs. C(n)

### ISSUE THREAD

**Issue by ColeFrench** [boazbk/crypto#104]
`o` is an alternative to `C(n)` for the length of a ciphertext, right? If so, this should probably be documented here: https://github.com/boazbk/crypto/blob/6b5b388bb672318b2a06dd15f19190e42b05b671/lec_01_introduction.md#L139-L155.

**Comment by boazbk** [comment]
What usage of o does this refer to?
Probably should be consistent, but it's hard - added a warning that we won't always be.
