### ISSUE TITLE
typos in proof of theorem 3.4

### ISSUE THREAD

**Issue by mshirazi** [boazbk/crypto#111]
As usual, we will use the hybrid argument. (...) to be the distribution where the first i bits chosen at **random**

And I think it should be $s_i$ chosen at random from $\{ 0, 1 \}^i$ as well (in the following line)

Just grammar, but better to drop the comma on "Now suppose otherwise, that there exists some adversary Eve such that ..." ("Now suppose otherwise that there exists some adversary Eve such that ...")

And on the following sentence, instead of "We will build from Eve an adversary Eve' breaking ...", make it "From Eve, we will build an adversary Eve' ..."

On following sentence, instead of "On input of string y", make it "On an input string y"

"Eve' will interpret $y$ as (s_i + 1, y_i + 1). Choose y_1, ..." (turn the comma into a period)

**Comment by boazbk** [comment]
Thanks!
