### ISSUE TITLE
Table clips off page in Lecture 20: Quantum/Crypto II

### ISSUE THREAD

**Issue by wfus** [boazbk/crypto#2]
Table clips off in PDF Version, weird formatting happens on the web version too.

<img width="1233" alt="screencap" src="https://user-images.githubusercontent.com/21962760/35286863-0d6f7734-002f-11e8-9a84-28bf9b161c11.png">

Here's the web version from my browser as well:

<img width="1413" alt="screen shot 2018-01-23 at 11 18 46 am" src="https://user-images.githubusercontent.com/21962760/35286980-627efaa6-002f-11e8-80c7-2dcf862f61f4.png">

**Comment by boazbk** [comment]
Thanks Wilson! It might take me a while to get to updating that lecture, so will leave the issue open
