### ISSUE TITLE
Lecture 2 Typos

### ISSUE THREAD

**Issue by gtanzer** [boazbk/crypto#3]
**Changes** and ~Deletions~ marked; it's difficult to bold punctuation in Markdown though

* "with messages that can much longer (sometimes even terrabytes or more of data)" &rarr; "with messages that can **be** much longer (sometimes even **terabytes** or more of data)"

* Theorem 2.3: "If (E, D) is has t bits of computational security as per Definition 2.4 then every" &rarr; "If (E,D) ~is~ has t bits of computational security as per Definition 2.4 then **for** every"

* "we will assume towards a contradiction, that there is an efficient adversay strategy" &rarr; "we will assume towards a contradiction, that there is an efficient **adversary** strategy"

* "and build from Eve a strategy Eve' demonstrating that S' violates X." &rarr; "and build from Eve a strategy Eve' demonstrating that S' violates X**'**."

* "for short) , which we will consider as efficient" &rarr; "for short), which we will consider as efficient**.**" (notice the extra space before the comma) (there also isn't a comma in the equivalent spot in the next bullet, but w/e) 

* "Note that for every non-constant polynomials p, q," &rarr; "Note that for **all** non-constant polynomials p, q,"

* "For concreteness, lets define that a function F ... has complexity at most T is there is a Boolean circuits that" &rarr; "For concreteness, let**'**s define that a function F ... has complexity at most T **if** there is a Boolean **circuit** that"

* "gate that outputs a single random bits (though" &rarr; "gate that outputs a single random **bit** (though"

* The Cipher Conjecture "There exists a computationally scure encryption scheme (E,D)" &rarr; "There exists a computationally **secure** encryption scheme (E,D)"

* "and hence in particular there must exists some i" &rarr; "and hence in particular there must **exist** some i"

* "Indeed, suppose towards the sake of contradction that there was" &rarr; "Indeed, suppose towards the sake of **contradiction** that there was"

* under Theorem 2.9 "some $T-10\ell n$-time $Eve's:{{0,1}}^{n\ell}\rightarrow{{0,1}}$" &rarr; some $T-10\ell n$-time $Eve'~s~:{{0,1}}^{n\ell}\rightarrow{{0,1}}$

* "$$ \left| {\mathbb{E}}[ Eve'(H_i) ] - {\mathbb{E}}[ Eve(H_{i+1}) ] \right| > \epsilon;. $$" &rarr; "$$ \left| {\mathbb{E}}[ Eve'(H_i) ] - {\mathbb{E}}[ Eve**'**(H_{i+1}) ] \right| > \epsilon;. $$"

* "variable $Z$ satisfies ${\mathbb{E}}Z \geq \alpha$" &rarr; "variable $Z$ satisfies ${\mathbb{E}}**[**Z**]** \geq \alpha$"

* "then $Eve$ runs in time at most the running time of $Eve$" &rarr; "then $Eve$ runs in time at most the running time of $Eve**'**$"

* "For a warm-up, let's show that the easier fact that" &rarr; "For a warm-up, let's show ~that~ the easier fact that"

* "Since we know that for every pair of message $m" &rarr; "Since we know that for every pair of message**s** $m"

**Comment by boazbk** [comment]
Thank you so much!!
