### ISSUE TITLE
Broken itemize groups in many chapters

### ISSUE THREAD

**Issue by wfus** [boazbk/crypto#35]
Not sure if this is intended, but it seems like there are a few broken itemize groups in the chapters where ```* item 1``` doesn't render correctly. Some samples are attached - 

<img width="522" alt="ex1" src="https://user-images.githubusercontent.com/21962760/39666447-cd383636-5071-11e8-95cf-1acdc7ede886.png">

```
>
Consider the following "box" $\hat{D}$ that will answer decryption queries $c\|y\|z$ of the adversary as follows: \
* If $z$ was returned before to the adversary as an answer to $H'(m\|r)$ for some $m,r$, and $c=E_e(m\;H(m\|r))$ and $y=m\oplus r$ then return $m$. \
* Otherwise return ```error```
>
```

I believe it is because of the ```\``` on the previous line before the itemize environment, but I might be wrong. Here's an example for when it renders correctly:

<img width="415" alt="screen shot 2018-05-05 at 2 39 51 pm" src="https://user-images.githubusercontent.com/21962760/39666484-316a14a8-5072-11e8-83a6-b3cae361e22d.png">

```
>__CCA-ROM-ENC Scheme:__
>
* **Ingredients:** A public key encryption scheme $(G',E',D')$ and a two hash functions $H,H':\{0,1\}^*\rightarrow\{0,1\}^n$ (which we model as independent random oracles[^oracles])
>
* **Key generation:** We generate keys $(e,d)=G'(1^n)$ for the underlying encryption scheme.
>
* **Encryption:** To encrypt a message $m\in\{0,1\}^\ell$, we select randomness $r\leftarrow_R\{0,1\}^\ell$ for the underlying encryption algorithm $E'$ and output $E'_e(r;H(m\|r))\|(r \oplus m)\|H'(m\|r)$, where by $E'_e(m';r')$ we denote the result of encrypting $m'$ using the key $e$ and the randomness $r'$ (we assume the scheme takes $n$ bits of randomness as input; otherwise modify the output length of $H$ accordingly).
>
* **Decryption:** To decrypt a ciphertext $c\|y\|z$ first let $r=D_d(c)$, $m=r \oplus y$ and then check that $c=E_e(m;H(m\|r))$ and $z=H'(m\|r)$. If any of the checks fail we output ```error```; otherwise we output $m$.
```

**Comment by boazbk** [comment]
Yes I haven't completely figured out how to do itemize correctly. Often if
I don't add this \ then there is no line break

**Comment by boazbk** [comment]
I believe it's fixed now
