### ISSUE TITLE
QKE 

### ISSUE THREAD

**Issue by wilsonqin** [boazbk/crypto#38]
Saw this in recent ACM news digest.
Maybe relevant to future edits of the PKE / Key Exchange chapters:

https://www.siliconrepublic.com/enterprise/bt-unhackable-network

> The link is said to be ‘unhackable’ due to its reliance on the use of single particles of light (photons) to transmit encryption keys across the fibre. If this communication is intercepted, the sender will be able to detect that the link has been tampered with.

**Comment by boazbk** [comment]
Thanks!

**Comment by boazbk** [comment]
I might try to add something about quantum key distribution later on if I get time, but for now closing this issue
