### ISSUE TITLE
Build tooling for typesetting

### ISSUE THREAD

**Issue by amontalenti** [boazbk/crypto#40]
This is a really amazing textbook you have put together. I am wondering, could you include your typesetting toolchain in the source tree here, e.g. the Makefile that might build this Markdown into the PDFs and HTML you have published?

**Comment by boazbk** [comment]
Thanks, but I didn't do it. The scripts we're written by David Steurer of ETH. I believe he plans to release them at some point after he makes it less fragile, but you can contact him to ask for a copy.
