### ISSUE TITLE
Possibility of providing exercises/problem sets

### ISSUE THREAD

**Issue by silasdavis** [boazbk/crypto#41]
Thanks very much for making these notes available, but please sir, can I have some more...

I wonder if you are able to make available some of the exercises/problem sets referred to by the text? I suspect you may wish to avoid disseminating graded problem sets, but thought I would ask. Perhaps you might be able to provide suggested exercises from other texts/locations.

**Comment by boazbk** [comment]
Thank you! I am updated these notes every time I teach the course, and so the next time would be Spring 2020 (and indeed i prefer to avoid disseminating problem sets). However, the Boneh-Shoup text https://crypto.stanford.edu/~dabo/cryptobook/ (draft available online) has a number of great exercises.

**Comment by silasdavis** [comment]
perfect, thank you, and thanks again for the course - some of it will be directly relevant to future work on a project I maintain: https://github.com/hyperledger/burrow
