### ISSUE TITLE
Makefile or instructions missing

### ISSUE THREAD

**Issue by tilman-schieber** [boazbk/crypto#43]
There is no makefile or explanation in the readme.md how this is compiled to a pdf.
Not even a reference to the used software (pandoc?)
This would be helpful both for people trying to contribute and lecturers trying to create similarly beautiful scripts.

**Comment by boazbk** [comment]
I added a little explanation in the readme.md I am using a set of scripts written by David Steurer that is still in somewhat fragile state (I have a hard time compiling it when I move to a new machine). The scripts are written on top of pandoc and the tufte css and latex packages. I use a variant of this in sumofsquares.org and introtcs.org (though in the latter I moved away from Tufte CSS and to the Distill css).

I believe David plans at some point to publish his scripts, after he gets them into a less fragile state.
