### ISSUE TITLE
Intersecting column notes

### ISSUE THREAD

**Issue by sundogx** [boazbk/crypto#57]
Formatting issue where column notes too long intersect one beneath them, like page 153 and 156 of https://files.boazbarak.org/crypto/lnotes_book.pdf

**Comment by boazbk** [comment]
Yes this is one of the harder ones to debug, there is something in the latex package for side notes that is not so great. I will look into this.

**Comment by boazbk** [comment]
Hope it's fixed but I think I won't be debugging side notes for now
