### ISSUE TITLE
Typo in page 73

### ISSUE THREAD

**Issue by silviacasac** [boazbk/crypto#97]
"etc" should be "etc."

**Comment by silviacasac** [comment]
Same page: "__Negligible probabilities__" I assume was meant to be italicized?

**Comment by silviacasac** [comment]
Missing "." right before Exercise 2.1.

**Comment by boazbk** [comment]
Thanks! (But for future ones, please use section numbers and ideally also their titles rather than page numbers, since the latter tend to change every time I compile)

**Comment by silviacasac** [comment]
Okay, will do! Sorry
